[gym]
id = 115

[top_rope]
grade_min = "5c"
grade_max = "6c"

[lead]
grade_min = "5b"
grade_max = "6b"

# gym.id
# Climb Up Aix Bouc Bel Air         115
# Climb Up Aubagne                  229
# Climb Up Aubervilliers            274
# Climb Up Angers                   201
# Climb Up Bordeaux - Mérignac      161
# Climb Up Bordeaux - Villenave      53
# Climb Up Brest                    194
# Climb Up Cergy                    260
# Climb Up Chambéry                  82
# Climb Up Dijon                      5
# Climb Up Épinay                    67
# Climb Up Istres                   663
# Climb Up Le Mans                  423
# Climb Up Lille Centre             228
# Climb Up Lille Lesquin             43
# Climb Up Lille Villeneuve d'Ascq   42
# Climb Up Lille Wambrechies         41
# Climb Up Limoges                   25
# Climb Up Lyon Confluence            4
# Climb Up Lyon Gerland               3
# Climb Up Nancy                    181
# Climb Up Orléans                  111
# Climb Up Paris Porte d'Italie     218
# Climb Up Saint Étienne            259
# Climb Up Wittenheim               219